export const COUNTRIES = [
  { code: "AR", label: "Argentina", flag: "🇦🇷" },
  { code: "AU", label: "Australia", flag: "🇦🇺" },
  { code: "AT", label: "Austria", flag: "🇦🇹" },
  { code: "BE", label: "Belgium", flag: "🇧🇪" },
  { code: "BR", label: "Brazil", flag: "🇧🇷" },
  { code: "BG", label: "Bulgaria", flag: "🇧🇬" },
  { code: "CA", label: "Canada", flag: "🇨🇦" },
  { code: "CL", label: "Chile", flag: "🇨🇱" },
  { code: "CN", label: "China", flag: "🇨🇳" },
  { code: "CO", label: "Colombia", flag: "🇨🇴" },
  { code: "HR", label: "Croatia", flag: "🇭🇷" },
  { code: "CZ", label: "Czech Republic", flag: "🇨🇿" },
  { code: "DK", label: "Denmark", flag: "🇩🇰" },
  { code: "EG", label: "Egypt", flag: "🇪🇬" },
  { code: "FI", label: "Finland", flag: "🇫🇮" },
  { code: "FR", label: "France", flag: "🇫🇷" },
  { code: "DE", label: "Germany", flag: "🇩🇪" },
  { code: "GR", label: "Greece", flag: "🇬🇷" },
  { code: "HU", label: "Hungary", flag: "🇭🇺" },
  { code: "IN", label: "India", flag: "🇮🇳" },
  { code: "ID", label: "Indonesia", flag: "🇮🇩" },
  { code: "IE", label: "Ireland", flag: "🇮🇪" },
  { code: "IL", label: "Israel", flag: "🇮🇱" },
  { code: "IT", label: "Italy", flag: "🇮🇹" },
  { code: "JP", label: "Japan", flag: "🇯🇵" },
  { code: "KR", label: "South Korea", flag: "🇰🇷" },
  { code: "MX", label: "Mexico", flag: "🇲🇽" },
  { code: "NL", label: "Netherlands", flag: "🇳🇱" },
  { code: "NZ", label: "New Zealand", flag: "🇳🇿" },
  { code: "NG", label: "Nigeria", flag: "🇳🇬" },
  { code: "NO", label: "Norway", flag: "🇳🇴" },
  { code: "PE", label: "Peru", flag: "🇵🇪" },
  { code: "PH", label: "Philippines", flag: "🇵🇭" },
  { code: "PL", label: "Poland", flag: "🇵🇱" },
  { code: "PT", label: "Portugal", flag: "🇵🇹" },
  { code: "RO", label: "Romania", flag: "🇷🇴" },
  { code: "SA", label: "Saudi Arabia", flag: "🇸🇦" },
  { code: "RS", label: "Serbia", flag: "🇷🇸" },
  { code: "SG", label: "Singapore", flag: "🇸🇬" },
  { code: "ZA", label: "South Africa", flag: "🇿🇦" },
  { code: "ES", label: "Spain", flag: "🇪🇸" },
  { code: "SE", label: "Sweden", flag: "🇸🇪" },
  { code: "CH", label: "Switzerland", flag: "🇨🇭" },
  { code: "TH", label: "Thailand", flag: "🇹🇭" },
  { code: "TR", label: "Turkey", flag: "🇹🇷" },
  { code: "UA", label: "Ukraine", flag: "🇺🇦" },
  { code: "AE", label: "United Arab Emirates", flag: "🇦🇪" },
  { code: "GB", label: "United Kingdom", flag: "🇬🇧" },
  { code: "US", label: "United States", flag: "🇺🇸" },
  { code: "VN", label: "Vietnam", flag: "🇻🇳" },
] as const

export function getFlagFromCode(code: string) {
  return COUNTRIES.find((c) => c.code === code)?.flag ?? "🏳️"
}

export function getCountryLabel(code: string) {
  return COUNTRIES.find((c) => c.code === code)?.label ?? code
}