export type AppLocale = "it" | "en"

export type DailyLanguageCode = "it" | "en" | "es" | "fr" | "de" | "ru" | "ja"

export type DailyFamily = "romance" | "germanic" | "slavic" | "japanese"

export type DailyScript = "latin" | "cyrillic" | "japanese"

export type DailyTranslation = {
  language: DailyLanguageCode
  value: string
  family: DailyFamily
  script: DailyScript
  note?: {
    it: string
    en: string
  }
}

export type DailyWord = {
  id: number
  dateKey: string
  lemmaIt: string
  lemmaEn: string
  emoji: string
  category:
    | "home"
    | "nature"
    | "food"
    | "body"
    | "city"
    | "time"
    | "animals"
    | "culture"
    | "travel"
  difficulty: "easy" | "medium" | "hard"
  translations: DailyTranslation[]
  insight: {
    it: string
    en: string
  }
}

function t(
  language: DailyLanguageCode,
  value: string,
  family: DailyFamily,
  script: DailyScript,
  note?: DailyTranslation["note"]
): DailyTranslation {
  return { language, value, family, script, note }
}

export const MAY_2026_DAILY_WORDS: DailyWord[] = [
  {
    id: 1,
    dateKey: "2026-05-01",
    lemmaIt: "casa",
    lemmaEn: "house",
    emoji: "🏠",
    category: "home",
    difficulty: "easy",
    translations: [
      t("it", "casa", "romance", "latin"),
      t("en", "house", "germanic", "latin"),
      t("es", "casa", "romance", "latin", {
        it: "Italiano e spagnolo condividono la stessa forma scritta.",
        en: "Italian and Spanish share the same written form.",
      }),
      t("fr", "maison", "romance", "latin"),
      t("de", "Haus", "germanic", "latin"),
      t("ru", "дом", "slavic", "cyrillic"),
      t("ja", "家", "japanese", "japanese"),
    ],
    insight: {
      it: "“Casa” è perfetta per iniziare: italiano e spagnolo coincidono nella forma scritta, mentre inglese e tedesco mostrano una parentela germanica con “house” e “Haus”.",
      en: "“House” is a strong starting word: Italian and Spanish share the same written form, while English and German show a Germanic connection through “house” and “Haus”.",
    },
  },
  {
    id: 2,
    dateKey: "2026-05-02",
    lemmaIt: "acqua",
    lemmaEn: "water",
    emoji: "💧",
    category: "nature",
    difficulty: "easy",
    translations: [
      t("it", "acqua", "romance", "latin"),
      t("en", "water", "germanic", "latin"),
      t("es", "agua", "romance", "latin"),
      t("fr", "eau", "romance", "latin"),
      t("de", "Wasser", "germanic", "latin"),
      t("ru", "вода", "slavic", "cyrillic"),
      t("ja", "水", "japanese", "japanese"),
    ],
    insight: {
      it: "Le lingue romanze mostrano forme molto diverse tra loro: “acqua”, “agua” ed “eau” vengono dalla stessa area storica, ma non sempre si assomigliano in superficie.",
      en: "Romance languages can look surprisingly different: “acqua”, “agua”, and “eau” belong to the same historical area, even when they do not look identical.",
    },
  },
  {
    id: 3,
    dateKey: "2026-05-03",
    lemmaIt: "pane",
    lemmaEn: "bread",
    emoji: "🍞",
    category: "food",
    difficulty: "easy",
    translations: [
      t("it", "pane", "romance", "latin"),
      t("en", "bread", "germanic", "latin"),
      t("es", "pan", "romance", "latin"),
      t("fr", "pain", "romance", "latin"),
      t("de", "Brot", "germanic", "latin"),
      t("ru", "хлеб", "slavic", "cyrillic"),
      t("ja", "パン", "japanese", "japanese", {
        it: "In giapponese “パン” è un prestito linguistico scritto in katakana.",
        en: "Japanese “パン” is a loanword written in katakana.",
      }),
    ],
    insight: {
      it: "“Pane”, “pan” e “pain” sono ottimi esempi di somiglianza romanza, mentre “パン” mostra come anche il giapponese possa assorbire parole straniere.",
      en: "“Pane”, “pan”, and “pain” are clear Romance-language relatives, while “パン” shows how Japanese can absorb foreign words.",
    },
  },
  {
    id: 4,
    dateKey: "2026-05-04",
    lemmaIt: "sole",
    lemmaEn: "sun",
    emoji: "☀️",
    category: "nature",
    difficulty: "easy",
    translations: [
      t("it", "sole", "romance", "latin"),
      t("en", "sun", "germanic", "latin"),
      t("es", "sol", "romance", "latin"),
      t("fr", "soleil", "romance", "latin"),
      t("de", "Sonne", "germanic", "latin"),
      t("ru", "солнце", "slavic", "cyrillic"),
      t("ja", "太陽", "japanese", "japanese"),
    ],
    insight: {
      it: "Il tema del sole mostra bene le famiglie linguistiche: “sun” e “Sonne” sono germaniche, mentre “sole”, “sol” e “soleil” si muovono nell’area romanza.",
      en: "The sun makes language families easy to see: “sun” and “Sonne” are Germanic, while “sole”, “sol”, and “soleil” sit in the Romance area.",
    },
  },
  {
    id: 5,
    dateKey: "2026-05-05",
    lemmaIt: "luna",
    lemmaEn: "moon",
    emoji: "🌙",
    category: "nature",
    difficulty: "easy",
    translations: [
      t("it", "luna", "romance", "latin"),
      t("en", "moon", "germanic", "latin"),
      t("es", "luna", "romance", "latin"),
      t("fr", "lune", "romance", "latin"),
      t("de", "Mond", "germanic", "latin"),
      t("ru", "луна", "slavic", "cyrillic"),
      t("ja", "月", "japanese", "japanese"),
    ],
    insight: {
      it: "“Luna” è quasi una scorciatoia per riconoscere le lingue romanze: italiano e spagnolo coincidono, francese resta vicino con “lune”.",
      en: "“Moon” highlights Romance similarities: Italian and Spanish share “luna”, and French stays close with “lune”.",
    },
  },
  {
    id: 6,
    dateKey: "2026-05-06",
    lemmaIt: "fuoco",
    lemmaEn: "fire",
    emoji: "🔥",
    category: "nature",
    difficulty: "medium",
    translations: [
      t("it", "fuoco", "romance", "latin"),
      t("en", "fire", "germanic", "latin"),
      t("es", "fuego", "romance", "latin"),
      t("fr", "feu", "romance", "latin"),
      t("de", "Feuer", "germanic", "latin"),
      t("ru", "огонь", "slavic", "cyrillic"),
      t("ja", "火", "japanese", "japanese"),
    ],
    insight: {
      it: "“Fuoco”, “fuego” e “feu” sembrano diverse, ma mantengono una parentela visibile. “Fire” e “Feuer” mostrano invece il ramo germanico.",
      en: "“Fuoco”, “fuego”, and “feu” look different but remain related. “Fire” and “Feuer” show the Germanic branch.",
    },
  },
  {
    id: 7,
    dateKey: "2026-05-07",
    lemmaIt: "terra",
    lemmaEn: "earth",
    emoji: "🌍",
    category: "nature",
    difficulty: "medium",
    translations: [
      t("it", "terra", "romance", "latin"),
      t("en", "earth", "germanic", "latin"),
      t("es", "tierra", "romance", "latin"),
      t("fr", "terre", "romance", "latin"),
      t("de", "Erde", "germanic", "latin"),
      t("ru", "земля", "slavic", "cyrillic"),
      t("ja", "地球", "japanese", "japanese"),
    ],
    insight: {
      it: "Le forme romanze “terra”, “tierra” e “terre” sono molto riconoscibili. Inglese e tedesco invece usano “earth” ed “Erde”.",
      en: "The Romance forms “terra”, “tierra”, and “terre” are highly recognizable. English and German use “earth” and “Erde”.",
    },
  },
  {
    id: 8,
    dateKey: "2026-05-08",
    lemmaIt: "mare",
    lemmaEn: "sea",
    emoji: "🌊",
    category: "nature",
    difficulty: "easy",
    translations: [
      t("it", "mare", "romance", "latin"),
      t("en", "sea", "germanic", "latin"),
      t("es", "mar", "romance", "latin"),
      t("fr", "mer", "romance", "latin"),
      t("de", "Meer", "germanic", "latin"),
      t("ru", "море", "slavic", "cyrillic"),
      t("ja", "海", "japanese", "japanese"),
    ],
    insight: {
      it: "“Mare”, “mar”, “mer” e perfino “Meer” sono una bella rete di somiglianze. Il mare, a quanto pare, collega anche le parole. Che cosa poetica, quasi sospetta.",
      en: "“Mare”, “mar”, “mer”, and even “Meer” form a neat network of similarities. The sea connects words too, apparently.",
    },
  },
  {
    id: 9,
    dateKey: "2026-05-09",
    lemmaIt: "montagna",
    lemmaEn: "mountain",
    emoji: "⛰️",
    category: "nature",
    difficulty: "medium",
    translations: [
      t("it", "montagna", "romance", "latin"),
      t("en", "mountain", "germanic", "latin"),
      t("es", "montaña", "romance", "latin"),
      t("fr", "montagne", "romance", "latin"),
      t("de", "Berg", "germanic", "latin"),
      t("ru", "гора", "slavic", "cyrillic"),
      t("ja", "山", "japanese", "japanese"),
    ],
    insight: {
      it: "Italiano, spagnolo e francese sono molto vicini qui: “montagna”, “montaña”, “montagne”. Il tedesco invece sceglie “Berg”, giusto per non renderla troppo facile.",
      en: "Italian, Spanish, and French stay close here: “montagna”, “montaña”, “montagne”. German goes with “Berg”, just to keep humans alert.",
    },
  },
  {
    id: 10,
    dateKey: "2026-05-10",
    lemmaIt: "albero",
    lemmaEn: "tree",
    emoji: "🌳",
    category: "nature",
    difficulty: "medium",
    translations: [
      t("it", "albero", "romance", "latin"),
      t("en", "tree", "germanic", "latin"),
      t("es", "árbol", "romance", "latin"),
      t("fr", "arbre", "romance", "latin"),
      t("de", "Baum", "germanic", "latin"),
      t("ru", "дерево", "slavic", "cyrillic"),
      t("ja", "木", "japanese", "japanese"),
    ],
    insight: {
      it: "“Albero”, “árbol” e “arbre” non sono identici, ma mostrano bene come le parole cambino forma restando nella stessa famiglia.",
      en: "“Albero”, “árbol”, and “arbre” are not identical, but they show how words can shift shape inside the same family.",
    },
  },
  {
    id: 11,
    dateKey: "2026-05-11",
    lemmaIt: "libro",
    lemmaEn: "book",
    emoji: "📚",
    category: "culture",
    difficulty: "easy",
    translations: [
      t("it", "libro", "romance", "latin"),
      t("en", "book", "germanic", "latin"),
      t("es", "libro", "romance", "latin"),
      t("fr", "livre", "romance", "latin"),
      t("de", "Buch", "germanic", "latin"),
      t("ru", "книга", "slavic", "cyrillic"),
      t("ja", "本", "japanese", "japanese"),
    ],
    insight: {
      it: "“Libro” è uguale in italiano e spagnolo, mentre il francese “livre” resta riconoscibile. Il tedesco “Buch” cambia completamente scena.",
      en: "“Libro” is identical in Italian and Spanish, while French “livre” remains recognizable. German “Buch” changes the whole scene.",
    },
  },
  {
    id: 12,
    dateKey: "2026-05-12",
    lemmaIt: "strada",
    lemmaEn: "road",
    emoji: "🛣️",
    category: "city",
    difficulty: "medium",
    translations: [
      t("it", "strada", "romance", "latin"),
      t("en", "road", "germanic", "latin"),
      t("es", "camino", "romance", "latin"),
      t("fr", "route", "romance", "latin"),
      t("de", "Straße", "germanic", "latin"),
      t("ru", "дорога", "slavic", "cyrillic"),
      t("ja", "道", "japanese", "japanese"),
    ],
    insight: {
      it: "“Strada” e “Straße” si somigliano molto, anche se appartengono a rami diversi. È uno di quei casi in cui la linguistica si diverte a complicare la vita.",
      en: "“Strada” and “Straße” look very close despite belonging to different branches. Language enjoys making things unnecessarily dramatic.",
    },
  },
  {
    id: 13,
    dateKey: "2026-05-13",
    lemmaIt: "amico",
    lemmaEn: "friend",
    emoji: "🤝",
    category: "culture",
    difficulty: "easy",
    translations: [
      t("it", "amico", "romance", "latin"),
      t("en", "friend", "germanic", "latin"),
      t("es", "amigo", "romance", "latin"),
      t("fr", "ami", "romance", "latin"),
      t("de", "Freund", "germanic", "latin"),
      t("ru", "друг", "slavic", "cyrillic"),
      t("ja", "友達", "japanese", "japanese"),
    ],
    insight: {
      it: "“Amico”, “amigo” e “ami” sono un trio romanzissimo. Inglese e tedesco invece si avvicinano con “friend” e “Freund”.",
      en: "“Amico”, “amigo”, and “ami” form a very Romance trio. English and German move together with “friend” and “Freund”.",
    },
  },
  {
    id: 14,
    dateKey: "2026-05-14",
    lemmaIt: "tempo",
    lemmaEn: "time",
    emoji: "⏳",
    category: "time",
    difficulty: "medium",
    translations: [
      t("it", "tempo", "romance", "latin"),
      t("en", "time", "germanic", "latin"),
      t("es", "tiempo", "romance", "latin"),
      t("fr", "temps", "romance", "latin"),
      t("de", "Zeit", "germanic", "latin"),
      t("ru", "время", "slavic", "cyrillic"),
      t("ja", "時間", "japanese", "japanese"),
    ],
    insight: {
      it: "“Tempo”, “tiempo” e “temps” mostrano una parentela romanza molto utile da riconoscere. “Zeit” invece arriva secco e tedesco come un promemoria fiscale.",
      en: "“Tempo”, “tiempo”, and “temps” show a useful Romance connection. “Zeit” arrives sharply German, like a tax reminder.",
    },
  },
  {
    id: 15,
    dateKey: "2026-05-15",
    lemmaIt: "notte",
    lemmaEn: "night",
    emoji: "🌌",
    category: "time",
    difficulty: "easy",
    translations: [
      t("it", "notte", "romance", "latin"),
      t("en", "night", "germanic", "latin"),
      t("es", "noche", "romance", "latin"),
      t("fr", "nuit", "romance", "latin"),
      t("de", "Nacht", "germanic", "latin"),
      t("ru", "ночь", "slavic", "cyrillic"),
      t("ja", "夜", "japanese", "japanese"),
    ],
    insight: {
      it: "“Night” e “Nacht” sono una coppia germanica chiara. “Notte”, “noche” e “nuit” raccontano invece la variazione romanza.",
      en: "“Night” and “Nacht” form a clear Germanic pair. “Notte”, “noche”, and “nuit” show Romance variation.",
    },
  },
  {
    id: 16,
    dateKey: "2026-05-16",
    lemmaIt: "giorno",
    lemmaEn: "day",
    emoji: "📅",
    category: "time",
    difficulty: "easy",
    translations: [
      t("it", "giorno", "romance", "latin"),
      t("en", "day", "germanic", "latin"),
      t("es", "día", "romance", "latin"),
      t("fr", "jour", "romance", "latin"),
      t("de", "Tag", "germanic", "latin"),
      t("ru", "день", "slavic", "cyrillic"),
      t("ja", "日", "japanese", "japanese"),
    ],
    insight: {
      it: "Questa parola è utile perché le forme cambiano molto tra le lingue: riconoscere “jour”, “Tag” e “день” richiede memoria più che intuito.",
      en: "This word is useful because the forms vary a lot: recognizing “jour”, “Tag”, and “день” requires memory more than intuition.",
    },
  },
  {
    id: 17,
    dateKey: "2026-05-17",
    lemmaIt: "cuore",
    lemmaEn: "heart",
    emoji: "❤️",
    category: "body",
    difficulty: "medium",
    translations: [
      t("it", "cuore", "romance", "latin"),
      t("en", "heart", "germanic", "latin"),
      t("es", "corazón", "romance", "latin"),
      t("fr", "cœur", "romance", "latin"),
      t("de", "Herz", "germanic", "latin"),
      t("ru", "сердце", "slavic", "cyrillic"),
      t("ja", "心", "japanese", "japanese"),
    ],
    insight: {
      it: "“Cuore”, “cœur” e “corazón” hanno forme diverse ma una parentela storica. “Heart” e “Herz” invece sono una coppia germanica facile da notare.",
      en: "“Cuore”, “cœur”, and “corazón” look different but share history. “Heart” and “Herz” are an easy Germanic pair to notice.",
    },
  },
  {
    id: 18,
    dateKey: "2026-05-18",
    lemmaIt: "mano",
    lemmaEn: "hand",
    emoji: "✋",
    category: "body",
    difficulty: "easy",
    translations: [
      t("it", "mano", "romance", "latin"),
      t("en", "hand", "germanic", "latin"),
      t("es", "mano", "romance", "latin"),
      t("fr", "main", "romance", "latin"),
      t("de", "Hand", "germanic", "latin"),
      t("ru", "рука", "slavic", "cyrillic"),
      t("ja", "手", "japanese", "japanese"),
    ],
    insight: {
      it: "Italiano e spagnolo condividono “mano”. Inglese e tedesco condividono “hand/Hand”. È quasi tutto troppo ordinato, infatti non durerà.",
      en: "Italian and Spanish share “mano”. English and German share “hand/Hand”. Almost suspiciously tidy.",
    },
  },
  {
    id: 19,
    dateKey: "2026-05-19",
    lemmaIt: "occhio",
    lemmaEn: "eye",
    emoji: "👁️",
    category: "body",
    difficulty: "medium",
    translations: [
      t("it", "occhio", "romance", "latin"),
      t("en", "eye", "germanic", "latin"),
      t("es", "ojo", "romance", "latin"),
      t("fr", "œil", "romance", "latin"),
      t("de", "Auge", "germanic", "latin"),
      t("ru", "глаз", "slavic", "cyrillic"),
      t("ja", "目", "japanese", "japanese"),
    ],
    insight: {
      it: "“Occhio”, “ojo” e “œil” sono poco trasparenti, ma proprio per questo allenano bene il riconoscimento tra lingue romanze.",
      en: "“Occhio”, “ojo”, and “œil” are not immediately transparent, which makes them great Romance-recognition training.",
    },
  },
  {
    id: 20,
    dateKey: "2026-05-20",
    lemmaIt: "porta",
    lemmaEn: "door",
    emoji: "🚪",
    category: "home",
    difficulty: "easy",
    translations: [
      t("it", "porta", "romance", "latin"),
      t("en", "door", "germanic", "latin"),
      t("es", "puerta", "romance", "latin"),
      t("fr", "porte", "romance", "latin"),
      t("de", "Tür", "germanic", "latin"),
      t("ru", "дверь", "slavic", "cyrillic"),
      t("ja", "ドア", "japanese", "japanese", {
        it: "“ドア” è scritto in katakana ed è un prestito dall’inglese “door”.",
        en: "“ドア” is written in katakana and is a loanword from English “door”.",
      }),
    ],
    insight: {
      it: "“Porta”, “puerta” e “porte” mostrano bene la variazione romanza. Il giapponese “ドア” è invece un prestito moderno.",
      en: "“Porta”, “puerta”, and “porte” show Romance variation. Japanese “ドア” is a modern loanword.",
    },
  },
  {
    id: 21,
    dateKey: "2026-05-21",
    lemmaIt: "scuola",
    lemmaEn: "school",
    emoji: "🏫",
    category: "culture",
    difficulty: "easy",
    translations: [
      t("it", "scuola", "romance", "latin"),
      t("en", "school", "germanic", "latin"),
      t("es", "escuela", "romance", "latin"),
      t("fr", "école", "romance", "latin"),
      t("de", "Schule", "germanic", "latin"),
      t("ru", "школа", "slavic", "cyrillic"),
      t("ja", "学校", "japanese", "japanese"),
    ],
    insight: {
      it: "Questa parola è piena di parentela visibile: “school”, “Schule” e “школа” si riconoscono bene, anche cambiando alfabeto.",
      en: "This word has visible family ties: “school”, “Schule”, and “школа” remain recognizable even across scripts.",
    },
  },
  {
    id: 22,
    dateKey: "2026-05-22",
    lemmaIt: "città",
    lemmaEn: "city",
    emoji: "🏙️",
    category: "city",
    difficulty: "medium",
    translations: [
      t("it", "città", "romance", "latin"),
      t("en", "city", "germanic", "latin"),
      t("es", "ciudad", "romance", "latin"),
      t("fr", "ville", "romance", "latin"),
      t("de", "Stadt", "germanic", "latin"),
      t("ru", "город", "slavic", "cyrillic"),
      t("ja", "都市", "japanese", "japanese"),
    ],
    insight: {
      it: "“Città”, “city” e “ciudad” sembrano vicine, ma francese e tedesco cambiano strada con “ville” e “Stadt”.",
      en: "“Città”, “city”, and “ciudad” look close, while French and German take different paths with “ville” and “Stadt”.",
    },
  },
  {
    id: 23,
    dateKey: "2026-05-23",
    lemmaIt: "stella",
    lemmaEn: "star",
    emoji: "⭐",
    category: "nature",
    difficulty: "easy",
    translations: [
      t("it", "stella", "romance", "latin"),
      t("en", "star", "germanic", "latin"),
      t("es", "estrella", "romance", "latin"),
      t("fr", "étoile", "romance", "latin"),
      t("de", "Stern", "germanic", "latin"),
      t("ru", "звезда", "slavic", "cyrillic"),
      t("ja", "星", "japanese", "japanese"),
    ],
    insight: {
      it: "“Star” e “Stern” sono molto vicine. Le lingue romanze qui sono meno immediate: “stella”, “estrella”, “étoile”.",
      en: "“Star” and “Stern” are very close. Romance forms are less immediate here: “stella”, “estrella”, “étoile”.",
    },
  },
  {
    id: 24,
    dateKey: "2026-05-24",
    lemmaIt: "vento",
    lemmaEn: "wind",
    emoji: "🌬️",
    category: "nature",
    difficulty: "easy",
    translations: [
      t("it", "vento", "romance", "latin"),
      t("en", "wind", "germanic", "latin"),
      t("es", "viento", "romance", "latin"),
      t("fr", "vent", "romance", "latin"),
      t("de", "Wind", "germanic", "latin"),
      t("ru", "ветер", "slavic", "cyrillic"),
      t("ja", "風", "japanese", "japanese"),
    ],
    insight: {
      it: "“Wind” e “Wind” sono identici tra inglese e tedesco nella forma scritta, anche se la pronuncia cambia. Finalmente una cosa semplice. Incredibile.",
      en: "English “wind” and German “Wind” are identical in writing, although pronunciation differs. A rare merciful moment.",
    },
  },
  {
    id: 25,
    dateKey: "2026-05-25",
    lemmaIt: "fiore",
    lemmaEn: "flower",
    emoji: "🌸",
    category: "nature",
    difficulty: "medium",
    translations: [
      t("it", "fiore", "romance", "latin"),
      t("en", "flower", "germanic", "latin"),
      t("es", "flor", "romance", "latin"),
      t("fr", "fleur", "romance", "latin"),
      t("de", "Blume", "germanic", "latin"),
      t("ru", "цветок", "slavic", "cyrillic"),
      t("ja", "花", "japanese", "japanese"),
    ],
    insight: {
      it: "“Fiore”, “flor” e “fleur” sono un trio romanza molto utile. “Flower” è vicino, ma arriva dal ramo germanico.",
      en: "“Fiore”, “flor”, and “fleur” are a useful Romance trio. “Flower” looks close but belongs to the Germanic branch.",
    },
  },
  {
    id: 26,
    dateKey: "2026-05-26",
    lemmaIt: "cane",
    lemmaEn: "dog",
    emoji: "🐶",
    category: "animals",
    difficulty: "easy",
    translations: [
      t("it", "cane", "romance", "latin"),
      t("en", "dog", "germanic", "latin"),
      t("es", "perro", "romance", "latin"),
      t("fr", "chien", "romance", "latin"),
      t("de", "Hund", "germanic", "latin"),
      t("ru", "собака", "slavic", "cyrillic"),
      t("ja", "犬", "japanese", "japanese"),
    ],
    insight: {
      it: "Questa parola è ottima perché le forme cambiano molto. “Dog”, “chien”, “Hund” e “собака” non ti regalano grandi scorciatoie.",
      en: "This word is great because forms vary a lot. “Dog”, “chien”, “Hund”, and “собака” do not offer many shortcuts.",
    },
  },
  {
    id: 27,
    dateKey: "2026-05-27",
    lemmaIt: "gatto",
    lemmaEn: "cat",
    emoji: "🐱",
    category: "animals",
    difficulty: "easy",
    translations: [
      t("it", "gatto", "romance", "latin"),
      t("en", "cat", "germanic", "latin"),
      t("es", "gato", "romance", "latin"),
      t("fr", "chat", "romance", "latin"),
      t("de", "Katze", "germanic", "latin"),
      t("ru", "кошка", "slavic", "cyrillic"),
      t("ja", "猫", "japanese", "japanese"),
    ],
    insight: {
      it: "“Gatto”, “gato”, “cat” e “Katze” permettono di vedere somiglianze e distanze insieme. Il gatto resta superiore in ogni lingua, purtroppo lo sa.",
      en: "“Gatto”, “gato”, “cat”, and “Katze” show similarities and distances at once. The cat remains superior in every language, and knows it.",
    },
  },
  {
    id: 28,
    dateKey: "2026-05-28",
    lemmaIt: "cibo",
    lemmaEn: "food",
    emoji: "🍽️",
    category: "food",
    difficulty: "medium",
    translations: [
      t("it", "cibo", "romance", "latin"),
      t("en", "food", "germanic", "latin"),
      t("es", "comida", "romance", "latin"),
      t("fr", "nourriture", "romance", "latin"),
      t("de", "Essen", "germanic", "latin"),
      t("ru", "еда", "slavic", "cyrillic"),
      t("ja", "食べ物", "japanese", "japanese"),
    ],
    insight: {
      it: "“Cibo” cambia parecchio tra le lingue. Qui il riconoscimento non può basarsi solo sulla somiglianza grafica: bisogna imparare davvero. Tremendo, lo so.",
      en: "“Food” changes quite a lot across languages. Recognition cannot rely only on visual similarity here: actual learning is required. Tragic.",
    },
  },
  {
    id: 29,
    dateKey: "2026-05-29",
    lemmaIt: "musica",
    lemmaEn: "music",
    emoji: "🎵",
    category: "culture",
    difficulty: "easy",
    translations: [
      t("it", "musica", "romance", "latin"),
      t("en", "music", "germanic", "latin"),
      t("es", "música", "romance", "latin"),
      t("fr", "musique", "romance", "latin"),
      t("de", "Musik", "germanic", "latin"),
      t("ru", "музыка", "slavic", "cyrillic"),
      t("ja", "音楽", "japanese", "japanese"),
    ],
    insight: {
      it: "Questa è una parola internazionale: “musica”, “music”, “musique”, “Musik” e “музыка” sono sorprendentemente vicine.",
      en: "This is an international word: “musica”, “music”, “musique”, “Musik”, and “музыка” stay surprisingly close.",
    },
  },
  {
    id: 30,
    dateKey: "2026-05-30",
    lemmaIt: "luce",
    lemmaEn: "light",
    emoji: "💡",
    category: "nature",
    difficulty: "medium",
    translations: [
      t("it", "luce", "romance", "latin"),
      t("en", "light", "germanic", "latin"),
      t("es", "luz", "romance", "latin"),
      t("fr", "lumière", "romance", "latin"),
      t("de", "Licht", "germanic", "latin"),
      t("ru", "свет", "slavic", "cyrillic"),
      t("ja", "光", "japanese", "japanese"),
    ],
    insight: {
      it: "“Light” e “Licht” sono vicine. “Luce”, “luz” e “lumière” restano nell’area romanza, anche se il francese fa sempre un po’ il protagonista.",
      en: "“Light” and “Licht” are close. “Luce”, “luz”, and “lumière” stay in the Romance area, with French being dramatic as usual.",
    },
  },
  {
    id: 31,
    dateKey: "2026-05-31",
    lemmaIt: "viaggio",
    lemmaEn: "journey",
    emoji: "🧳",
    category: "travel",
    difficulty: "medium",
    translations: [
      t("it", "viaggio", "romance", "latin"),
      t("en", "journey", "germanic", "latin"),
      t("es", "viaje", "romance", "latin"),
      t("fr", "voyage", "romance", "latin"),
      t("de", "Reise", "germanic", "latin"),
      t("ru", "путешествие", "slavic", "cyrillic"),
      t("ja", "旅行", "japanese", "japanese"),
    ],
    insight: {
      it: "“Viaggio”, “viaje” e “voyage” sono una chiusura perfetta per maggio: parole vicine, ma non identiche. Il mese finisce, il lessico resta a giudicarti.",
      en: "“Viaggio”, “viaje”, and “voyage” close May nicely: related, but not identical. The month ends, vocabulary remains judgmental.",
    },
  },
]
