export type Question = {
  id: number
  text: string
  correct: string
  options?: string[]
}

export const questions: Question[] = [
  {
    id: 1,
    text: "Je ne comprends pas pourquoi tu fais ça.",
    correct: "Francese",
    options: ["Francese", "Tedesco", "Spagnolo", "Portoghese"],
  },
  {
    id: 2,
    text: "No entiendo lo que estás diciendo.",
    correct: "Spagnolo",
    options: ["Italiano", "Spagnolo", "Francese", "Rumeno"],
  },
  {
    id: 3,
    text: "Ich habe heute wirklich keine Zeit.",
    correct: "Tedesco",
    options: ["Olandese", "Tedesco", "Svedese", "Danese"],
  },
  {
    id: 4,
    text: "Ayer fui al mercado con mi hermano.",
    correct: "Spagnolo",
    options: ["Portoghese", "Spagnolo", "Italiano", "Francese"],
  },
  {
    id: 5,
    text: "今日はとてもいい天気ですね。",
    correct: "Giapponese",
    options: ["Cinese", "Coreano", "Giapponese", "Thailandese"],
  },
  {
    id: 6,
    text: "안녕하세요, 오늘 기분이 어때요?",
    correct: "Coreano",
    options: ["Giapponese", "Cinese", "Coreano", "Vietnamita"],
  },
  {
    id: 7,
    text: "Привет, как ты себя чувствуешь?",
    correct: "Russo",
    options: ["Ucraino", "Russo", "Bulgaro", "Polacco"],
  },
  {
    id: 8,
    text: "مرحبا كيف حالك اليوم",
    correct: "Arabo",
    options: ["Persiano", "Urdu", "Arabo", "Turco"],
  },
  {
    id: 9,
    text: "Eu não sei se isso é verdade.",
    correct: "Portoghese",
    options: ["Spagnolo", "Portoghese", "Italiano", "Francese"],
  },
  {
    id: 10,
    text: "Ik weet niet of dat een goed idee is.",
    correct: "Olandese",
    options: ["Tedesco", "Olandese", "Danese", "Svedese"],
  },
  {
    id: 11,
    text: "Merci beaucoup pour ton aide.",
    correct: "Francese",
    options: ["Francese", "Italiano", "Spagnolo", "Portoghese"],
  },
  {
    id: 12,
    text: "No puedo hacerlo sin tu ayuda.",
    correct: "Spagnolo",
    options: ["Spagnolo", "Portoghese", "Italiano", "Francese"],
  },
  {
    id: 13,
    text: "Wir gehen morgen zusammen ins Kino.",
    correct: "Tedesco",
    options: ["Olandese", "Tedesco", "Svedese", "Norvegese"],
  },
  {
    id: 14,
    text: "Hoje estou muito cansado depois do trabalho.",
    correct: "Portoghese",
    options: ["Spagnolo", "Portoghese", "Francese", "Italiano"],
  },
  {
    id: 15,
    text: "Dit is waarschijnlijk niet de beste oplossing.",
    correct: "Olandese",
    options: ["Tedesco", "Olandese", "Danese", "Inglese"],
  },
  {
    id: 16,
    text: "お名前は何ですか？",
    correct: "Giapponese",
    options: ["Cinese", "Coreano", "Giapponese", "Vietnamita"],
  },
  {
    id: 17,
    text: "저는 음악을 듣는 것을 좋아해요.",
    correct: "Coreano",
    options: ["Coreano", "Giapponese", "Cinese", "Thailandese"],
  },
  {
    id: 18,
    text: "Это очень интересная идея.",
    correct: "Russo",
    options: ["Russo", "Ucraino", "Serbo", "Bulgaro"],
  },
  {
    id: 19,
    text: "أريد أن أتعلم لغة جديدة",
    correct: "Arabo",
    options: ["Urdu", "Arabo", "Persiano", "Turco"],
  },
  {
    id: 20,
    text: "Je vais rentrer un peu plus tard ce soir.",
    correct: "Francese",
    options: ["Francese", "Spagnolo", "Italiano", "Portoghese"],
  },
  {
    id: 21,
    text: "Necesitamos hablar de algo importante.",
    correct: "Spagnolo",
    options: ["Italiano", "Portoghese", "Spagnolo", "Francese"],
  },
  {
    id: 22,
    text: "Kannst du mir bitte kurz helfen?",
    correct: "Tedesco",
    options: ["Tedesco", "Olandese", "Danese", "Svedese"],
  },
  {
    id: 23,
    text: "Amanhã vamos sair bem cedo.",
    correct: "Portoghese",
    options: ["Portoghese", "Spagnolo", "Italiano", "Rumeno"],
  },
  {
    id: 24,
    text: "We moeten straks echt vertrekken.",
    correct: "Olandese",
    options: ["Tedesco", "Olandese", "Norvegese", "Danese"],
  },
  {
    id: 25,
    text: "昨日はあまり眠れませんでした。",
    correct: "Giapponese",
    options: ["Coreano", "Giapponese", "Cinese", "Thailandese"],
  },
  {
    id: 26,
    text: "오늘 저녁에 뭐 먹을래요?",
    correct: "Coreano",
    options: ["Giapponese", "Coreano", "Cinese", "Vietnamita"],
  },
  {
    id: 27,
    text: "Я не знаю, что мне делать.",
    correct: "Russo",
    options: ["Russo", "Ucraino", "Polacco", "Ceco"],
  },
  {
    id: 28,
    text: "هذا المكان جميل جدا",
    correct: "Arabo",
    options: ["Arabo", "Persiano", "Urdu", "Turco"],
  },
  {
    id: 29,
    text: "Tu peux répéter une dernière fois ?",
    correct: "Francese",
    options: ["Francese", "Portoghese", "Spagnolo", "Italiano"],
  },
  {
    id: 30,
    text: "Ellos llegaron hace unos minutos.",
    correct: "Spagnolo",
    options: ["Portoghese", "Spagnolo", "Italiano", "Francese"],
  },
  {
    id: 31,
    text: "Heute ist ein perfekter Tag zum Spazierengehen.",
    correct: "Tedesco",
    options: ["Olandese", "Tedesco", "Norvegese", "Danese"],
  },
  {
    id: 32,
    text: "Eu preciso terminar isso hoje.",
    correct: "Portoghese",
    options: ["Spagnolo", "Portoghese", "Italiano", "Francese"],
  },
  {
    id: 33,
    text: "Hij begrijpt niet wat er gebeurt.",
    correct: "Olandese",
    options: ["Danese", "Tedesco", "Olandese", "Svedese"],
  },
  {
    id: 34,
    text: "これは本当に難しい質問です。",
    correct: "Giapponese",
    options: ["Coreano", "Giapponese", "Cinese", "Vietnamita"],
  },
  {
    id: 35,
    text: "저는 내일 서울에 갈 거예요.",
    correct: "Coreano",
    options: ["Cinese", "Coreano", "Giapponese", "Thailandese"],
  },
  {
    id: 36,
    text: "Мы скоро будем готовы.",
    correct: "Russo",
    options: ["Bulgaro", "Russo", "Ucraino", "Polacco"],
  },
  {
    id: 37,
    text: "هل يمكنك مساعدتي من فضلك",
    correct: "Arabo",
    options: ["Persiano", "Turco", "Arabo", "Urdu"],
  },
  {
    id: 38,
    text: "Je suis sûr que tout ira bien.",
    correct: "Francese",
    options: ["Francese", "Italiano", "Spagnolo", "Portoghese"],
  },
  {
    id: 39,
    text: "Todavía no he terminado este libro.",
    correct: "Spagnolo",
    options: ["Portoghese", "Spagnolo", "Italiano", "Francese"],
  },
  {
    id: 40,
    text: "Das ist nicht so einfach, wie es aussieht.",
    correct: "Tedesco",
    options: ["Tedesco", "Olandese", "Danese", "Svedese"],
  },
  {
    id: 41,
    text: "A gente pode conversar depois.",
    correct: "Portoghese",
    options: ["Portoghese", "Spagnolo", "Italiano", "Rumeno"],
  },
  {
    id: 42,
    text: "Ze willen vanavond thuis blijven.",
    correct: "Olandese",
    options: ["Olandese", "Tedesco", "Danese", "Svedese"],
  },
  {
    id: 43,
    text: "何を探しているんですか？",
    correct: "Giapponese",
    options: ["Giapponese", "Coreano", "Cinese", "Thailandese"],
  },
  {
    id: 44,
    text: "이건 생각보다 훨씬 어려워요.",
    correct: "Coreano",
    options: ["Coreano", "Giapponese", "Cinese", "Vietnamita"],
  },
  {
    id: 45,
    text: "Мне очень нравится эта песня.",
    correct: "Russo",
    options: ["Russo", "Ucraino", "Bulgaro", "Serbo"],
  },
  {
    id: 46,
    text: "أنا لا أفهم ما تقوله",
    correct: "Arabo",
    options: ["Urdu", "Arabo", "Persiano", "Turco"],
  },
  {
    id: 47,
    text: "Nous avons déjà réservé une table.",
    correct: "Francese",
    options: ["Francese", "Italiano", "Spagnolo", "Portoghese"],
  },
  {
    id: 48,
    text: "Necesito un poco más de tiempo.",
    correct: "Spagnolo",
    options: ["Spagnolo", "Italiano", "Portoghese", "Francese"],
  },
  {
    id: 49,
    text: "Ich glaube, du hast recht.",
    correct: "Tedesco",
    options: ["Olandese", "Tedesco", "Danese", "Norvegese"],
  },
  {
    id: 50,
    text: "Eles ainda não chegaram aqui.",
    correct: "Portoghese",
    options: ["Portoghese", "Spagnolo", "Italiano", "Rumeno"],
  },
    {
    id: 51,
    text: "Bu sabah seni aradım ama cevap vermedin.",
    correct: "Turco",
    options: ["Turco", "Persiano", "Arabo", "Urdu"],
  },
  {
    id: 52,
    text: "Bugün hava sandığımdan daha soğuk.",
    correct: "Turco",
    options: ["Turco", "Arabo", "Persiano", "Russo"],
  },
  {
    id: 53,
    text: "Bu gerçekten düşündüğümden daha zor.",
    correct: "Turco",
    options: ["Turco", "Urdu", "Persiano", "Arabo"],
  },
  {
    id: 54,
    text: "امروز خیلی خسته‌ام و می‌خواهم استراحت کنم.",
    correct: "Persiano",
    options: ["Persiano", "Arabo", "Urdu", "Turco"],
  },
  {
    id: 55,
    text: "فکر می‌کنم این ایده خیلی جالب باشد.",
    correct: "Persiano",
    options: ["Persiano", "Urdu", "Arabo", "Turco"],
  },
  {
    id: 56,
    text: "Vi ses måske i morgen efter arbejde.",
    correct: "Danese",
    options: ["Danese", "Svedese", "Norvegese", "Olandese"],
  },
  {
    id: 57,
    text: "Det här är mycket svårare än jag trodde.",
    correct: "Svedese",
    options: ["Svedese", "Danese", "Norvegese", "Tedesco"],
  },
  {
    id: 58,
    text: "Jeg tror ikke dette er en god idé.",
    correct: "Norvegese",
    options: ["Norvegese", "Danese", "Svedese", "Olandese"],
  },
  {
    id: 59,
    text: "Привіт, я вже майже на місці.",
    correct: "Ucraino",
    options: ["Ucraino", "Russo", "Bulgaro", "Serbo"],
  },
  {
    id: 60,
    text: "Сьогодні вранці було дуже холодно.",
    correct: "Ucraino",
    options: ["Ucraino", "Russo", "Polacco", "Bulgaro"],
  },
  {
    id: 61,
    text: "Това е много интересна възможност.",
    correct: "Bulgaro",
    options: ["Bulgaro", "Serbo", "Russo", "Ucraino"],
  },
  {
    id: 62,
    text: "Mislim da ovo nije bio dobar plan.",
    correct: "Serbo",
    options: ["Serbo", "Bulgaro", "Ceco", "Russo"],
  },
  {
    id: 63,
    text: "Myslím, že tohle není správné řešení.",
    correct: "Ceco",
    options: ["Ceco", "Polacco", "Serbo", "Bulgaro"],
  },
  {
    id: 64,
    text: "你好，我今天有点累。",
    correct: "Cinese",
    options: ["Cinese", "Giapponese", "Coreano", "Thailandese"],
  },
  {
    id: 65,
    text: "สวัสดี วันนี้คุณเป็นอย่างไรบ้าง",
    correct: "Thailandese",
    options: ["Thailandese", "Vietnamita", "Cinese", "Coreano"],
  },
  {
    id: 66,
    text: "Xin chào, hôm nay bạn có khỏe không?",
    correct: "Vietnamita",
    options: ["Vietnamita", "Thailandese", "Cinese", "Coreano"],
  },
    {
    id: 67,
    text: "Non riesco a capire cosa stai cercando di dire.",
    correct: "Italiano",
    options: ["Italiano", "Spagnolo", "Portoghese", "Francese"],
  },
  {
    id: 68,
    text: "Domani mattina dobbiamo uscire molto presto.",
    correct: "Italiano",
    options: ["Italiano", "Rumeno", "Spagnolo", "Francese"],
  },
  {
    id: 69,
    text: "Non pensavo fosse così difficile davvero.",
    correct: "Italiano",
    options: ["Italiano", "Portoghese", "Spagnolo", "Rumeno"],
  },
  {
    id: 70,
    text: "Hai già deciso cosa fare questo weekend?",
    correct: "Italiano",
    options: ["Italiano", "Francese", "Spagnolo", "Portoghese"],
  },
  {
    id: 71,
    text: "Nu înțeleg de ce ai făcut asta.",
    correct: "Rumeno",
    options: ["Rumeno", "Italiano", "Spagnolo", "Portoghese"],
  },
  {
    id: 72,
    text: "Cred că asta este o idee foarte bună.",
    correct: "Rumeno",
    options: ["Rumeno", "Italiano", "Francese", "Portoghese"],
  },
  {
    id: 73,
    text: "Mâine mergem împreună la piață.",
    correct: "Rumeno",
    options: ["Rumeno", "Italiano", "Spagnolo", "Francese"],
  },
  {
    id: 74,
    text: "Nu am avut timp să termin totul astăzi.",
    correct: "Rumeno",
    options: ["Rumeno", "Italiano", "Portoghese", "Spagnolo"],
  },
  {
    id: 75,
    text: "Nie rozumiem, co próbujesz powiedzieć.",
    correct: "Polacco",
    options: ["Polacco", "Ceco", "Ucraino", "Russo"],
  },
  {
    id: 76,
    text: "To jest znacznie trudniejsze niż myślałem.",
    correct: "Polacco",
    options: ["Polacco", "Ceco", "Bulgaro", "Serbo"],
  },
  {
    id: 77,
    text: "Wczoraj wieczorem wróciłem bardzo późno.",
    correct: "Polacco",
    options: ["Polacco", "Ucraino", "Russo", "Ceco"],
  },
  {
    id: 78,
    text: "Musimy porozmawiać o czymś ważnym.",
    correct: "Polacco",
    options: ["Polacco", "Ceco", "Serbo", "Bulgaro"],
  },
  {
    id: 79,
    text: "میں نہیں جانتا کہ تم کیا کہہ رہے ہو۔",
    correct: "Urdu",
    options: ["Urdu", "Arabo", "Persiano", "Turco"],
  },
  {
    id: 80,
    text: "آج موسم کافی بہتر لگ رہا ہے۔",
    correct: "Urdu",
    options: ["Urdu", "Persiano", "Arabo", "Turco"],
  },
  {
    id: 81,
    text: "مجھے لگتا ہے کہ یہ اچھا خیال ہے۔",
    correct: "Urdu",
    options: ["Urdu", "Persiano", "Arabo", "Turco"],
  },
  {
    id: 82,
    text: "ہم کل صبح جلدی نکلیں گے۔",
    correct: "Urdu",
    options: ["Urdu", "Arabo", "Persiano", "Turco"],
  },
  {
    id: 83,
    text: "我不知道你为什么这么做。",
    correct: "Cinese",
    options: ["Cinese", "Giapponese", "Coreano", "Thailandese"],
  },
  {
    id: 84,
    text: "今天晚上我们一起去吃饭吧。",
    correct: "Cinese",
    options: ["Cinese", "Giapponese", "Coreano", "Vietnamita"],
  },
  {
    id: 85,
    text: "这个问题比我想象的更难。",
    correct: "Cinese",
    options: ["Cinese", "Coreano", "Giapponese", "Thailandese"],
  },
  {
    id: 86,
    text: "你今天看起来有点累。",
    correct: "Cinese",
    options: ["Cinese", "Giapponese", "Coreano", "Vietnamita"],
  },
  {
    id: 87,
    text: "ผมคิดว่านี่ไม่ใช่ความคิดที่ดี",
    correct: "Thailandese",
    options: ["Thailandese", "Vietnamita", "Cinese", "Coreano"],
  },
  {
    id: 88,
    text: "วันนี้ฉันต้องกลับบ้านเร็วหน่อย",
    correct: "Thailandese",
    options: ["Thailandese", "Vietnamita", "Cinese", "Giapponese"],
  },
  {
    id: 89,
    text: "Tôi không nghĩ đây là ý kiến hay.",
    correct: "Vietnamita",
    options: ["Vietnamita", "Thailandese", "Cinese", "Coreano"],
  },
  {
    id: 90,
    text: "Hôm qua tôi đã về nhà rất muộn.",
    correct: "Vietnamita",
    options: ["Vietnamita", "Thailandese", "Cinese", "Coreano"],
  },
  {
    id: 91,
    text: "Jeg vet ikke om dette er riktig valg.",
    correct: "Norvegese",
    options: ["Norvegese", "Danese", "Svedese", "Olandese"],
  },
  {
    id: 92,
    text: "Vi må snakke sammen senere i kveld.",
    correct: "Norvegese",
    options: ["Norvegese", "Danese", "Svedese", "Tedesco"],
  },
  {
    id: 93,
    text: "Не мисля, че това е добра идея.",
    correct: "Bulgaro",
    options: ["Bulgaro", "Russo", "Ucraino", "Serbo"],
  },
  {
    id: 94,
    text: "Днес имам твърде много работа.",
    correct: "Bulgaro",
    options: ["Bulgaro", "Serbo", "Russo", "Polacco"],
  },
  {
    id: 95,
    text: "Mislim da ćemo stići na vreme.",
    correct: "Serbo",
    options: ["Serbo", "Bulgaro", "Ceco", "Polacco"],
  },
  {
    id: 96,
    text: "Juče nisam imao vremena za to.",
    correct: "Serbo",
    options: ["Serbo", "Bulgaro", "Ceco", "Ucraino"],
  },
  {id: 97, text: "La pluie tombe doucement sur les toits de la ville.", correct: "Francese"},
{id: 98, text: "Je ne comprends pas pourquoi tout le monde rit maintenant.", correct: "Francese"},
{id: 99, text: "Esta noche vamos a cenar tarde con toda la familia.", correct: "Spagnolo"},
{id: 100, text: "No sé si volveré mañana por la mañana.", correct: "Spagnolo"},
{id: 101, text: "Hoje o céu está limpo e o mar parece calmo.", correct: "Portoghese"},
{id: 102, text: "Eu preciso falar com você antes de sair.", correct: "Portoghese"},
{id: 103, text: "Domani pomeriggio passo da te dopo il lavoro.", correct: "Italiano"},
{id: 104, text: "Non pensavo che sarebbe finita in questo modo.", correct: "Italiano"},
{id: 105, text: "Mâine mergem împreună la piață dacă ai timp.", correct: "Rumeno"},
{id: 106, text: "Nu cred că el știe deja adevărul.", correct: "Rumeno"},

{id: 107, text: "Heute ist das Wetter besser als gestern.", correct: "Tedesco"},
{id: 108, text: "Ich habe keine Ahnung, was er sagen wollte.", correct: "Tedesco"},
{id: 109, text: "Ik weet niet of hij vandaag nog komt.", correct: "Olandese"},
{id: 110, text: "De kinderen spelen buiten in de tuin.", correct: "Olandese"},
{id: 111, text: "Jeg tror ikke, at hun kommer i morgen.", correct: "Danese"},
{id: 112, text: "Vi skal mødes foran stationen klokken otte.", correct: "Danese"},
{id: 113, text: "Jag förstår inte varför du är så arg.", correct: "Svedese"},
{id: 114, text: "Barnen vill inte gå och lägga sig ännu.", correct: "Svedese"},
{id: 115, text: "Jeg vet ikke om dette er den riktige veien.", correct: "Norvegese"},
{id: 116, text: "Vi må dra før det blir mørkt ute.", correct: "Norvegese"},

{id: 117, text: "Я не знаю, когда он вернётся домой.", correct: "Russo"},
{id: 118, text: "Сегодня вечером мы будем смотреть фильм.", correct: "Russo"},
{id: 119, text: "Я не думаю, що це хороша ідея.", correct: "Ucraino"},
{id: 120, text: "Сьогодні вранці було дуже холодно.", correct: "Ucraino"},
{id: 121, text: "Nie wiem, czy ona mówi prawdę.", correct: "Polacco"},
{id: 122, text: "Wczoraj wróciliśmy do domu bardzo późno.", correct: "Polacco"},
{id: 123, text: "Nevím, jestli to opravdu funguje.", correct: "Ceco"},
{id: 124, text: "Dnes večer půjdu pěšky domů.", correct: "Ceco"},
{id: 125, text: "Не искам да тръгвам толкова рано.", correct: "Bulgaro"},
{id: 126, text: "Вчера говорих с него по телефона.", correct: "Bulgaro"},

{id: 127, text: "Bugün dışarı çıkmak istemiyorum çünkü çok yorgunum.", correct: "Turco"},
{id: 128, text: "Bence bu karar doğru değil.", correct: "Turco"},
{id: 129, text: "من نمی‌دانم چرا او هنوز اینجاست.", correct: "Persiano"},
{id: 130, text: "امروز هوا خیلی بهتر از دیروز است.", correct: "Persiano"},
{id: 131, text: "میں نہیں جانتا کہ وہ کب آئے گا۔", correct: "Urdu"},
{id: 132, text: "آج رات ہم سب ایک ساتھ کھانا کھائیں گے۔", correct: "Urdu"},
{id: 133, text: "أنا لا أفهم لماذا تأخرت كل هذا الوقت.", correct: "Arabo"},
{id: 134, text: "اليوم الجو جميل جدا في المدينة.", correct: "Arabo"},

{id: 135, text: "今日は少し疲れたので早く寝ます。", correct: "Giapponese"},
{id: 136, text: "駅の近くで友達を待っています。", correct: "Giapponese"},
{id: 137, text: "오늘은 집에서 쉬고 싶어요.", correct: "Coreano"},
{id: 138, text: "저는 아직 그 소식을 듣지 못했어요.", correct: "Coreano"},
{id: 139, text: "我今天晚上不想出门。", correct: "Cinese"},
{id: 140, text: "我们明天一起去吃饭吧。", correct: "Cinese"},
{id: 141, text: "วันนี้ฉันไม่อยากออกไปข้างนอก", correct: "Thailandese"},
{id: 142, text: "พรุ่งนี้เราจะไปตลาดด้วยกัน", correct: "Thailandese"},
{id: 143, text: "Hôm nay tôi không muốn đi ra ngoài.", correct: "Vietnamita"},
{id: 144, text: "Chúng ta sẽ gặp nhau vào ngày mai.", correct: "Vietnamita"},
{id: 145, text: "Je pensais que tu arriverais plus tôt ce matin.", correct: "Francese"},
{id: 146, text: "Ils habitent encore dans la même rue qu’avant.", correct: "Francese"},
{id: 147, text: "No quiero hablar de eso ahora mismo.", correct: "Spagnolo"},
{id: 148, text: "A veces la respuesta más simple es la mejor.", correct: "Spagnolo"},
{id: 149, text: "Eu ainda não sei o que vou fazer amanhã.", correct: "Portoghese"},
{id: 150, text: "Ela sempre chega cedo quando tem uma reunião importante.", correct: "Portoghese"},
{id: 151, text: "Non era necessario aspettare così tanto per dirlo.", correct: "Italiano"},
{id: 152, text: "Questa mattina il treno è arrivato con mezz’ora di ritardo.", correct: "Italiano"},
{id: 153, text: "Nu înțeleg de ce ai spus asta ieri.", correct: "Rumeno"},
{id: 154, text: "Poate mergem acolo împreună săptămâna viitoare.", correct: "Rumeno"},

{id: 155, text: "Wir haben gestern lange über dieses Problem gesprochen.", correct: "Tedesco"},
{id: 156, text: "Niemand wusste, dass du schon zurück warst.", correct: "Tedesco"},
{id: 157, text: "Ik heb hem gisteren nog in het centrum gezien.", correct: "Olandese"},
{id: 158, text: "We moeten morgen vroeger vertrekken.", correct: "Olandese"},
{id: 159, text: "Jeg har aldrig set noget lignende før.", correct: "Danese"},
{id: 160, text: "Hun sagde, at hun ville komme senere.", correct: "Danese"},
{id: 161, text: "Jag tror att vi borde vänta lite till.", correct: "Svedese"},
{id: 162, text: "Han förstod inte frågan första gången.", correct: "Svedese"},
{id: 163, text: "Jeg tror vi finner veien uten hjelp.", correct: "Norvegese"},
{id: 164, text: "Hun sa at hun kom tilbake i morgen.", correct: "Norvegese"},

{id: 165, text: "Я думаю, что мы уже опоздали.", correct: "Russo"},
{id: 166, text: "Он никогда не говорит всей правды.", correct: "Russo"},
{id: 167, text: "Сьогодні ми працюємо до самого вечора.", correct: "Ucraino"},
{id: 168, text: "Я не знаю, де вони зараз знаходяться.", correct: "Ucraino"},
{id: 169, text: "Nie mamy wystarczająco dużo czasu.", correct: "Polacco"},
{id: 170, text: "To było znacznie trudniejsze, niż myślałem.", correct: "Polacco"},

{id: 171, text: "Δεν ξέρω αν θα έρθει σήμερα το βράδυ.", correct: "Greco"},
{id: 172, text: "Αύριο θα πάμε μαζί στην πόλη.", correct: "Greco"},
{id: 173, text: "Μου είπε ότι δεν έχει χρόνο τώρα.", correct: "Greco"},
{id: 174, text: "Το πρωί ήταν πολύ ήσυχα εδώ.", correct: "Greco"},
{id: 175, text: "Πρέπει να φύγουμε πριν νυχτώσει.", correct: "Greco"},
{id: 176, text: "Δεν κατάλαβα τι ήθελε να πει.", correct: "Greco"},
{id: 177, text: "Σήμερα ο καιρός είναι καλύτερος από χθες.", correct: "Greco"},
{id: 178, text: "Όλοι περίμεναν την ίδια απάντηση.", correct: "Greco"},
{id: 179, text: "Η μητέρα μου τηλεφώνησε πριν από λίγο.", correct: "Greco"},
{id: 180, text: "Αυτό το μέρος μου φαίνεται πολύ γνώριμο.", correct: "Greco"}
]