export type Question = {
  id: number
  text: string
  correct: string
  options: string[]
}

export const questions: Question[] = [
  {
    id: 1,
    text: "Je ne comprends pas pourquoi tu fais ça.",
    correct: "Francese",
    options: ["Francese", "Tedesco", "Spagnolo", "Portoghese"],
  },
  {
    id: 2,
    text: "No entiendo lo que estás diciendo.",
    correct: "Spagnolo",
    options: ["Italiano", "Spagnolo", "Francese", "Rumeno"],
  },
  {
    id: 3,
    text: "Ich habe heute wirklich keine Zeit.",
    correct: "Tedesco",
    options: ["Olandese", "Tedesco", "Svedese", "Danese"],
  },
  {
    id: 4,
    text: "Ayer fui al mercado con mi hermano.",
    correct: "Spagnolo",
    options: ["Portoghese", "Spagnolo", "Italiano", "Francese"],
  },
  {
    id: 5,
    text: "今日はとてもいい天気ですね。",
    correct: "Giapponese",
    options: ["Cinese", "Coreano", "Giapponese", "Thailandese"],
  },
  {
    id: 6,
    text: "안녕하세요, 오늘 기분이 어때요?",
    correct: "Coreano",
    options: ["Giapponese", "Cinese", "Coreano", "Vietnamita"],
  },
  {
    id: 7,
    text: "Привет, как ты себя чувствуешь?",
    correct: "Russo",
    options: ["Ucraino", "Russo", "Bulgaro", "Polacco"],
  },
  {
    id: 8,
    text: "مرحبا كيف حالك اليوم",
    correct: "Arabo",
    options: ["Persiano", "Urdu", "Arabo", "Turco"],
  },
  {
    id: 9,
    text: "Eu não sei se isso é verdade.",
    correct: "Portoghese",
    options: ["Spagnolo", "Portoghese", "Italiano", "Francese"],
  },
  {
    id: 10,
    text: "Ik weet niet of dat een goed idee is.",
    correct: "Olandese",
    options: ["Tedesco", "Olandese", "Danese", "Svedese"],
  },
  {
    id: 11,
    text: "Merci beaucoup pour ton aide.",
    correct: "Francese",
    options: ["Francese", "Italiano", "Spagnolo", "Portoghese"],
  },
  {
    id: 12,
    text: "No puedo hacerlo sin tu ayuda.",
    correct: "Spagnolo",
    options: ["Spagnolo", "Portoghese", "Italiano", "Francese"],
  },
  {
    id: 13,
    text: "Wir gehen morgen zusammen ins Kino.",
    correct: "Tedesco",
    options: ["Olandese", "Tedesco", "Svedese", "Norvegese"],
  },
  {
    id: 14,
    text: "Hoje estou muito cansado depois do trabalho.",
    correct: "Portoghese",
    options: ["Spagnolo", "Portoghese", "Francese", "Italiano"],
  },
  {
    id: 15,
    text: "Dit is waarschijnlijk niet de beste oplossing.",
    correct: "Olandese",
    options: ["Tedesco", "Olandese", "Danese", "Inglese"],
  },
  {
    id: 16,
    text: "お名前は何ですか？",
    correct: "Giapponese",
    options: ["Cinese", "Coreano", "Giapponese", "Vietnamita"],
  },
  {
    id: 17,
    text: "저는 음악을 듣는 것을 좋아해요.",
    correct: "Coreano",
    options: ["Coreano", "Giapponese", "Cinese", "Thailandese"],
  },
  {
    id: 18,
    text: "Это очень интересная идея.",
    correct: "Russo",
    options: ["Russo", "Ucraino", "Serbo", "Bulgaro"],
  },
  {
    id: 19,
    text: "أريد أن أتعلم لغة جديدة",
    correct: "Arabo",
    options: ["Urdu", "Arabo", "Persiano", "Turco"],
  },
  {
    id: 20,
    text: "Je vais rentrer un peu plus tard ce soir.",
    correct: "Francese",
    options: ["Francese", "Spagnolo", "Italiano", "Portoghese"],
  },
  {
    id: 21,
    text: "Necesitamos hablar de algo importante.",
    correct: "Spagnolo",
    options: ["Italiano", "Portoghese", "Spagnolo", "Francese"],
  },
  {
    id: 22,
    text: "Kannst du mir bitte kurz helfen?",
    correct: "Tedesco",
    options: ["Tedesco", "Olandese", "Danese", "Svedese"],
  },
  {
    id: 23,
    text: "Amanhã vamos sair bem cedo.",
    correct: "Portoghese",
    options: ["Portoghese", "Spagnolo", "Italiano", "Rumeno"],
  },
  {
    id: 24,
    text: "We moeten straks echt vertrekken.",
    correct: "Olandese",
    options: ["Tedesco", "Olandese", "Norvegese", "Danese"],
  },
  {
    id: 25,
    text: "昨日はあまり眠れませんでした。",
    correct: "Giapponese",
    options: ["Coreano", "Giapponese", "Cinese", "Thailandese"],
  },
  {
    id: 26,
    text: "오늘 저녁에 뭐 먹을래요?",
    correct: "Coreano",
    options: ["Giapponese", "Coreano", "Cinese", "Vietnamita"],
  },
  {
    id: 27,
    text: "Я не знаю, что мне делать.",
    correct: "Russo",
    options: ["Russo", "Ucraino", "Polacco", "Ceco"],
  },
  {
    id: 28,
    text: "هذا المكان جميل جدا",
    correct: "Arabo",
    options: ["Arabo", "Persiano", "Urdu", "Turco"],
  },
  {
    id: 29,
    text: "Tu peux répéter une dernière fois ?",
    correct: "Francese",
    options: ["Francese", "Portoghese", "Spagnolo", "Italiano"],
  },
  {
    id: 30,
    text: "Ellos llegaron hace unos minutos.",
    correct: "Spagnolo",
    options: ["Portoghese", "Spagnolo", "Italiano", "Francese"],
  },
  {
    id: 31,
    text: "Heute ist ein perfekter Tag zum Spazierengehen.",
    correct: "Tedesco",
    options: ["Olandese", "Tedesco", "Norvegese", "Danese"],
  },
  {
    id: 32,
    text: "Eu preciso terminar isso hoje.",
    correct: "Portoghese",
    options: ["Spagnolo", "Portoghese", "Italiano", "Francese"],
  },
  {
    id: 33,
    text: "Hij begrijpt niet wat er gebeurt.",
    correct: "Olandese",
    options: ["Danese", "Tedesco", "Olandese", "Svedese"],
  },
  {
    id: 34,
    text: "これは本当に難しい質問です。",
    correct: "Giapponese",
    options: ["Coreano", "Giapponese", "Cinese", "Vietnamita"],
  },
  {
    id: 35,
    text: "저는 내일 서울에 갈 거예요.",
    correct: "Coreano",
    options: ["Cinese", "Coreano", "Giapponese", "Thailandese"],
  },
  {
    id: 36,
    text: "Мы скоро будем готовы.",
    correct: "Russo",
    options: ["Bulgaro", "Russo", "Ucraino", "Polacco"],
  },
  {
    id: 37,
    text: "هل يمكنك مساعدتي من فضلك",
    correct: "Arabo",
    options: ["Persiano", "Turco", "Arabo", "Urdu"],
  },
  {
    id: 38,
    text: "Je suis sûr que tout ira bien.",
    correct: "Francese",
    options: ["Francese", "Italiano", "Spagnolo", "Portoghese"],
  },
  {
    id: 39,
    text: "Todavía no he terminado este libro.",
    correct: "Spagnolo",
    options: ["Portoghese", "Spagnolo", "Italiano", "Francese"],
  },
  {
    id: 40,
    text: "Das ist nicht so einfach, wie es aussieht.",
    correct: "Tedesco",
    options: ["Tedesco", "Olandese", "Danese", "Svedese"],
  },
  {
    id: 41,
    text: "A gente pode conversar depois.",
    correct: "Portoghese",
    options: ["Portoghese", "Spagnolo", "Italiano", "Rumeno"],
  },
  {
    id: 42,
    text: "Ze willen vanavond thuis blijven.",
    correct: "Olandese",
    options: ["Olandese", "Tedesco", "Danese", "Svedese"],
  },
  {
    id: 43,
    text: "何を探しているんですか？",
    correct: "Giapponese",
    options: ["Giapponese", "Coreano", "Cinese", "Thailandese"],
  },
  {
    id: 44,
    text: "이건 생각보다 훨씬 어려워요.",
    correct: "Coreano",
    options: ["Coreano", "Giapponese", "Cinese", "Vietnamita"],
  },
  {
    id: 45,
    text: "Мне очень нравится эта песня.",
    correct: "Russo",
    options: ["Russo", "Ucraino", "Bulgaro", "Serbo"],
  },
  {
    id: 46,
    text: "أنا لا أفهم ما تقوله",
    correct: "Arabo",
    options: ["Urdu", "Arabo", "Persiano", "Turco"],
  },
  {
    id: 47,
    text: "Nous avons déjà réservé une table.",
    correct: "Francese",
    options: ["Francese", "Italiano", "Spagnolo", "Portoghese"],
  },
  {
    id: 48,
    text: "Necesito un poco más de tiempo.",
    correct: "Spagnolo",
    options: ["Spagnolo", "Italiano", "Portoghese", "Francese"],
  },
  {
    id: 49,
    text: "Ich glaube, du hast recht.",
    correct: "Tedesco",
    options: ["Olandese", "Tedesco", "Danese", "Norvegese"],
  },
  {
    id: 50,
    text: "Eles ainda não chegaram aqui.",
    correct: "Portoghese",
    options: ["Portoghese", "Spagnolo", "Italiano", "Rumeno"],
  },
]